### ISSUE TITLE
E-mail verification link points to 127.0.0.1

### ISSUE THREAD

**Issue by zmyaro** [craigcabrey/ratemycoop#177] opened 2015-08-14 21:25 UTC
The e-mail verification link points to https://127.0.0.1/api/v1/Users/confirm?uid={uid}&redirect=/&token={token} instead of the domain of the instance (ratemycoop.io, for the live version).

**Comment by TLMcNulty** [comment] 2015-08-14 22:31
Duplicate of this issue.

**Comment by liam-middlebrook** [comment] 2015-08-17 05:11
Duplicate of #167

**Comment by kocsenc** [comment] 2015-10-02 03:24
We've been trying to fix this the right way; but it seems we'll have to hardcode the api root to the email.

**Comment by jcdesimp** [comment] 2015-10-02 21:27
@kocsenc the PR is waiting #182

**Comment by jcdesimp** [comment] 2015-10-03 03:27
fixed in #182

**Closed by jcdesimp** 2015-10-03 03:27 UTC

**Comment by msoucy** [comment] 2015-10-04 20:25
That doesn't quite seem like it actually fixes the issue, just hardcodes it even more.
